using System;
using System.Collections.Generic;

namespace VR.Electrical.Core
{
    /// <summary>
    /// Resolves CSV component names to generated Unity component script types.
    /// </summary>
    public static class ComponentRegistry
    {
        private static readonly Dictionary<string, Type> NameToType = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase)
        {
                { "Resistor", typeof(VR.Electrical.Components.ResistorComponent ) },
                { "Capacitor", typeof(VR.Electrical.Components.CapacitorComponent ) },
                { "Polar Capacitor", typeof(VR.Electrical.Components.PolarCapacitorComponent ) },
                { "Inductor", typeof(VR.Electrical.Components.InductorComponent ) },
                { "Potentiometer", typeof(VR.Electrical.Components.PotentiometerComponent ) },
                { "Memristor", typeof(VR.Electrical.Components.MemristorComponent ) },
                { "Spark Gap", typeof(VR.Electrical.Components.SparkGapComponent ) },
                { "Fuse", typeof(VR.Electrical.Components.FuseComponent ) },
                { "Crystal", typeof(VR.Electrical.Components.CrystalComponent ) },
                { "Thermistor NTC", typeof(VR.Electrical.Components.ThermistorNtcComponent ) },
                { "LDR", typeof(VR.Electrical.Components.LdrComponent ) },
                { "Diode", typeof(VR.Electrical.Components.DiodeComponent ) },
                { "Zener Diode", typeof(VR.Electrical.Components.ZenerDiodeComponent ) },
                { "LED", typeof(VR.Electrical.Components.LedComponent ) },
                { "LED Array", typeof(VR.Electrical.Components.LedArrayComponent ) },
                { "Tunnel Diode", typeof(VR.Electrical.Components.TunnelDiodeComponent ) },
                { "Varactor", typeof(VR.Electrical.Components.VaractorComponent ) },
                { "SCR", typeof(VR.Electrical.Components.ScrComponent ) },
                { "DIAC", typeof(VR.Electrical.Components.DiacComponent ) },
                { "TRIAC", typeof(VR.Electrical.Components.TriacComponent ) },
                { "NPN Transistor", typeof(VR.Electrical.Components.NpnTransistorComponent ) },
                { "PNP Transistor", typeof(VR.Electrical.Components.PnpTransistorComponent ) },
                { "N-MOSFET", typeof(VR.Electrical.Components.NMosfetComponent ) },
                { "P-MOSFET", typeof(VR.Electrical.Components.PMosfetComponent ) },
                { "N-JFET", typeof(VR.Electrical.Components.NJfetComponent ) },
                { "Darlington (NPN)", typeof(VR.Electrical.Components.DarlingtonNpnComponent ) },
                { "Darlington (PNP)", typeof(VR.Electrical.Components.DarlingtonPnpComponent ) },
                { "Unijunction Transistor", typeof(VR.Electrical.Components.UnijunctionTransistorComponent ) },
                { "DC Voltage Source", typeof(VR.Electrical.Components.DcVoltageSourceComponent ) },
                { "AC Voltage Source", typeof(VR.Electrical.Components.AcVoltageSourceComponent ) },
                { "Current Source", typeof(VR.Electrical.Components.CurrentSourceComponent ) },
                { "Rail (DC)", typeof(VR.Electrical.Components.RailDcComponent ) },
                { "AC Rail", typeof(VR.Electrical.Components.AcRailComponent ) },
                { "Square Rail", typeof(VR.Electrical.Components.SquareRailComponent ) },
                { "Variable Rail", typeof(VR.Electrical.Components.VariableRailComponent ) },
                { "Antenna", typeof(VR.Electrical.Components.AntennaComponent ) },
                { "Noise Source", typeof(VR.Electrical.Components.NoiseSourceComponent ) },
                { "AM Source", typeof(VR.Electrical.Components.AmSourceComponent ) },
                { "FM Source", typeof(VR.Electrical.Components.FmSourceComponent ) },
                { "Sweep", typeof(VR.Electrical.Components.SweepComponent ) },
                { "External Voltage", typeof(VR.Electrical.Components.ExternalVoltageComponent ) },
                { "Switch (SPST)", typeof(VR.Electrical.Components.SwitchSpstComponent ) },
                { "Switch (SPDT)", typeof(VR.Electrical.Components.SwitchSpdtComponent ) },
                { "Push Switch", typeof(VR.Electrical.Components.PushSwitchComponent ) },
                { "DPDT Switch", typeof(VR.Electrical.Components.DpdtSwitchComponent ) },
                { "MBB Switch", typeof(VR.Electrical.Components.MbbSwitchComponent ) },
                { "Cross Switch", typeof(VR.Electrical.Components.CrossSwitchComponent ) },
                { "Analog Switch", typeof(VR.Electrical.Components.AnalogSwitchComponent ) },
                { "Analog Switch 2", typeof(VR.Electrical.Components.AnalogSwitch2Component ) },
                { "Transformer", typeof(VR.Electrical.Components.TransformerComponent ) },
                { "Tapped Transformer", typeof(VR.Electrical.Components.TappedTransformerComponent ) },
                { "Custom Transformer", typeof(VR.Electrical.Components.CustomTransformerComponent ) },
                { "Transmission Line", typeof(VR.Electrical.Components.TransmissionLineComponent ) },
                { "Relay", typeof(VR.Electrical.Components.RelayComponent ) },
                { "Relay Coil", typeof(VR.Electrical.Components.RelayCoilComponent ) },
                { "Relay Contact", typeof(VR.Electrical.Components.RelayContactComponent ) },
                { "Time Delay Relay", typeof(VR.Electrical.Components.TimeDelayRelayComponent ) },
                { "Optocoupler", typeof(VR.Electrical.Components.OptocouplerComponent ) },
                { "Op-Amp (Ideal)", typeof(VR.Electrical.Components.OpAmpIdealComponent ) },
                { "Op-Amp (Real)", typeof(VR.Electrical.Components.OpAmpRealComponent ) },
                { "Op-Amp Swap", typeof(VR.Electrical.Components.OpAmpSwapComponent ) },
                { "OTA", typeof(VR.Electrical.Components.OtaComponent ) },
                { "Comparator", typeof(VR.Electrical.Components.ComparatorComponent ) },
                { "CC2 (CCII+)", typeof(VR.Electrical.Components.Cc2CciiComponent ) },
                { "Triode", typeof(VR.Electrical.Components.TriodeComponent ) },
                { "VCCS", typeof(VR.Electrical.Components.VccsComponent ) },
                { "VCVS", typeof(VR.Electrical.Components.VcvsComponent ) },
                { "CCCS", typeof(VR.Electrical.Components.CccsComponent ) },
                { "CCVS", typeof(VR.Electrical.Components.CcvsComponent ) },
                { "VCO", typeof(VR.Electrical.Components.VcoComponent ) },
                { "AND Gate", typeof(VR.Electrical.Components.AndGateComponent ) },
                { "NAND Gate", typeof(VR.Electrical.Components.NandGateComponent ) },
                { "OR Gate", typeof(VR.Electrical.Components.OrGateComponent ) },
                { "NOR Gate", typeof(VR.Electrical.Components.NorGateComponent ) },
                { "XOR Gate", typeof(VR.Electrical.Components.XorGateComponent ) },
                { "Inverter", typeof(VR.Electrical.Components.InverterComponent ) },
                { "Tri-State Buffer", typeof(VR.Electrical.Components.TriStateBufferComponent ) },
                { "Schmitt Trigger", typeof(VR.Electrical.Components.SchmittTriggerComponent ) },
                { "Inverting Schmitt", typeof(VR.Electrical.Components.InvertingSchmittComponent ) },
                { "Logic Input", typeof(VR.Electrical.Components.LogicInputComponent ) },
                { "Logic Output", typeof(VR.Electrical.Components.LogicOutputComponent ) },
                { "D Flip-Flop", typeof(VR.Electrical.Components.DFlipFlopComponent ) },
                { "JK Flip-Flop", typeof(VR.Electrical.Components.JkFlipFlopComponent ) },
                { "T Flip-Flop", typeof(VR.Electrical.Components.TFlipFlopComponent ) },
                { "Counter", typeof(VR.Electrical.Components.CounterComponent ) },
                { "Counter 2", typeof(VR.Electrical.Components.Counter2Component ) },
                { "Ring Counter", typeof(VR.Electrical.Components.RingCounterComponent ) },
                { "Latch", typeof(VR.Electrical.Components.LatchComponent ) },
                { "Timer (555)", typeof(VR.Electrical.Components.Timer555Component ) },
                { "DAC", typeof(VR.Electrical.Components.DacComponent ) },
                { "ADC", typeof(VR.Electrical.Components.AdcComponent ) },
                { "SRAM", typeof(VR.Electrical.Components.SramComponent ) },
                { "Seven Segment", typeof(VR.Electrical.Components.SevenSegmentComponent ) },
                { "7-Seg Decoder", typeof(VR.Electrical.Components.C7SegDecoderComponent ) },
                { "Half Adder", typeof(VR.Electrical.Components.HalfAdderComponent ) },
                { "Full Adder", typeof(VR.Electrical.Components.FullAdderComponent ) },
                { "Multiplexer", typeof(VR.Electrical.Components.MultiplexerComponent ) },
                { "Demultiplexer", typeof(VR.Electrical.Components.DemultiplexerComponent ) },
                { "SIPO Shift Register", typeof(VR.Electrical.Components.SipoShiftRegisterComponent ) },
                { "PISO Shift Register", typeof(VR.Electrical.Components.PisoShiftRegisterComponent ) },
                { "Phase Comparator", typeof(VR.Electrical.Components.PhaseComparatorComponent ) },
                { "Monostable", typeof(VR.Electrical.Components.MonostableComponent ) },
                { "Sequence Generator", typeof(VR.Electrical.Components.SequenceGeneratorComponent ) },
                { "Custom Logic", typeof(VR.Electrical.Components.CustomLogicComponent ) },
                { "Decimal Display", typeof(VR.Electrical.Components.DecimalDisplayComponent ) },
                { "Delay Buffer", typeof(VR.Electrical.Components.DelayBufferComponent ) },
                { "DC Motor", typeof(VR.Electrical.Components.DcMotorComponent ) },
                { "3-Phase Motor", typeof(VR.Electrical.Components.C3PhaseMotorComponent ) },
                { "Motor Protection Switch", typeof(VR.Electrical.Components.MotorProtectionSwitchComponent ) },
                { "Probe", typeof(VR.Electrical.Components.ProbeComponent ) },
                { "Test Point", typeof(VR.Electrical.Components.TestPointComponent ) },
                { "Ammeter", typeof(VR.Electrical.Components.AmmeterComponent ) },
                { "Ohm Meter", typeof(VR.Electrical.Components.OhmMeterComponent ) },
                { "Wattmeter", typeof(VR.Electrical.Components.WattmeterComponent ) },
                { "Output", typeof(VR.Electrical.Components.OutputComponent ) },
                { "Data Recorder", typeof(VR.Electrical.Components.DataRecorderComponent ) },
                { "Data Input", typeof(VR.Electrical.Components.DataInputComponent ) },
                { "Audio Output", typeof(VR.Electrical.Components.AudioOutputComponent ) },
                { "Audio Input", typeof(VR.Electrical.Components.AudioInputComponent ) },
                { "Stop Trigger", typeof(VR.Electrical.Components.StopTriggerComponent ) },
                { "Scope", typeof(VR.Electrical.Components.ScopeComponent ) },
                { "Lamp", typeof(VR.Electrical.Components.LampComponent ) },
                { "Wire", typeof(VR.Electrical.Components.WireComponent ) },
                { "Ground", typeof(VR.Electrical.Components.GroundComponent ) },
                { "Labeled Node", typeof(VR.Electrical.Components.LabeledNodeComponent ) },
                { "Text", typeof(VR.Electrical.Components.TextComponent ) },
                { "Box", typeof(VR.Electrical.Components.BoxComponent ) },
                { "Line", typeof(VR.Electrical.Components.LineComponent ) },
                { "Clock", typeof(VR.Electrical.Components.ClockComponent ) },
                { "Composite Element", typeof(VR.Electrical.Components.CompositeElementComponent ) },
                { "Custom Composite", typeof(VR.Electrical.Components.CustomCompositeComponent ) },
                { "Custom Composite Chip", typeof(VR.Electrical.Components.CustomCompositeChipComponent ) },
                { "CircuitElm", typeof(VR.Electrical.Components.CircuitelmComponent ) },
                { "GraphicElm", typeof(VR.Electrical.Components.GraphicelmComponent ) },
                { "CirSim", typeof(VR.Electrical.Components.CirsimComponent ) },
        };

        public static bool TryGetComponentType(string csvComponentName, out Type componentType)
        {
            return NameToType.TryGetValue(csvComponentName, out componentType);
        }

        public static IReadOnlyDictionary<string, Type> GetAllMappings()
        {
            return NameToType;
        }
    }
}
